
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# Rutas principales del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent
WALLET_DIR = BASE_DIR / "wallet"


# Cargar variables del archivo .env
load_dotenv(BASE_DIR / ".env")


def obtener_variable(nombre):
    """
    Obtiene una variable de entorno obligatoria.
    Si no existe o está vacía, detiene la aplicación con un mensaje claro.
    """
    valor = os.getenv(nombre)

    if not valor:
        raise ValueError(
            f"Falta configurar la variable {nombre} en el archivo .env"
        )

    return valor


# Seguridad
SECRET_KEY = obtener_variable("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

ALLOWED_HOSTS = [
    host.strip()
    for host in obtener_variable("ALLOWED_HOSTS").split(",")
    if host.strip()
]


# Aplicaciones instaladas
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'storages',
    "tareas",
]


# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"


# Plantillas
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Base de datos Oracle Autonomous Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.oracle",
        "NAME": obtener_variable("ORACLE_DSN"),
        "USER": obtener_variable("ORACLE_USER"),
        "PASSWORD": obtener_variable("ORACLE_PASSWORD"),
        "OPTIONS": {
            "config_dir": str(WALLET_DIR),
            "wallet_location": str(WALLET_DIR),
            "wallet_password": obtener_variable(
                "ORACLE_WALLET_PASSWORD"
            ),
        },
    }
}


# Validación de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internacionalización
LANGUAGE_CODE = "es-cl"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True


# Archivos estáticos
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Tipo de clave primaria predeterminada
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- Configuración de Azure Blob Storage ---

AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_CONTAINER = os.getenv('AZURE_CONTAINER', 'media')

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_ACCOUNT_NAME,
            "account_key": AZURE_ACCOUNT_KEY,
            "azure_container": AZURE_CONTAINER,
            "expiration_secs": 3600,
            "overwrite_files": True,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --- Fin configuración Azure Blob Storage ---